language: python

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
        keyurl: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - llvm-3.8

python: '3.5'

install:
  - 'pip install -r requirements.txt'
  - 'pip install -r dev-requirements.txt'

script: pytest
