language: python

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
        keyurl: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - llvm-3.8
      - llvm-3.8-dev

python: '3.5'

install:
  - 'LLVM_CONFIG=llvm-config-3.8 pip install -r requirements.txt'
  - 'pip install -r dev-requirements.txt'

script: pytest

notifications:
  email: false
